node {

    def app

    stage('Clone Repository') {

        checkout scm

    }

    stage('Build') {

        app = docker.build("react-app")

    }

    stage('Test') {

        docker.image("react-app").inside {

            sh 'echo "Running tests..."'

            sh 'CI=true npm test --watchAll=false || true'

        }

    }

    stage('Push Image') {

        echo 'Skipping push for local build'

    }

}
